'use client'

import { Button } from "@/components/ui/button"
import { usePcBuilderStore } from "@/store/usePcBuilderStore"
import jsPDF from 'jspdf'
import 'jspdf-autotable'
import {
    Cpu,
    Disc,
    Fan,
    HardDrive,
    Headphones,
    Keyboard,
    Laptop,
    Monitor,
    Mouse,
    Zap
} from "lucide-react"
import { ComponentRow } from "./component-row"

const COMPONENT_SLOTS = [
  { type: 'cpu', label: 'Processor', icon: Cpu },
  { type: 'cooler', label: 'CPU Cooler', icon: Fan },
  { type: 'motherboard', label: 'Motherboard', icon: Laptop },
  { type: 'ram-1', label: 'RAM 1', icon: Disc, category: 'RAM' },
  { type: 'ram-2', label: 'RAM 2', icon: Disc, category: 'RAM' },
  { type: 'storage-1', label: 'Storage 1', icon: HardDrive, category: 'Storage' },
  { type: 'storage-2', label: 'Storage 2', icon: HardDrive, category: 'Storage' },
  { type: 'gpu', label: 'Graphics Card', icon: Cpu },
  { type: 'psu', label: 'Power Supply', icon: Zap },
  { type: 'casing', label: 'Casing', icon: Laptop },
  { type: 'monitor', label: 'Monitor', icon: Monitor },
  { type: 'keyboard', label: 'Keyboard', icon: Keyboard },
  { type: 'mouse', label: 'Mouse', icon: Mouse },
  { type: 'headphone', label: 'Headphone', icon: Headphones },
  { type: 'ups', label: 'UPS', icon: Zap },
]

import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
    AlertDialogTrigger,
} from "@/components/ui/alert-dialog"
import { Trash2 } from "lucide-react"

export function BuilderLayout() {
  const { totalPrice, components, clearBuild } = usePcBuilderStore()

  const handleDownloadPDF = () => {
    const doc = new jsPDF()
    
    // Header
    doc.setFontSize(22)
    doc.setTextColor(40, 40, 40)
    doc.text("PC Build Quotation", 14, 20)
    
    doc.setFontSize(12)
    doc.setTextColor(100, 100, 100)
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 30)
    doc.text("Generated by TechNexus PC Builder", 14, 36)

    // Table Data
    const tableData = Object.entries(components).map(([type, product]) => {
      const slot = COMPONENT_SLOTS.find(s => s.type === type)
      return [
        slot?.label || type,
        product.name,
        `Tk ${Number(product.price).toLocaleString()}`
      ]
    })

    // Add Total Row
    tableData.push(['', 'Total Amount', `Tk ${totalPrice.toLocaleString()}`])

    doc.autoTable({
      startY: 45,
      head: [['Component', 'Product Name', 'Price']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [66, 66, 66] },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 40 },
        2: { halign: 'right', fontStyle: 'bold', cellWidth: 40 }
      },
      footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' }
    })

    doc.save("my-pc-build.pdf")
  }

  return (
    <div className="grid lg:grid-cols-4 gap-8 relative">
      {/* Component List */}
      <div className="lg:col-span-3 space-y-4">
        {COMPONENT_SLOTS.map((slot) => (
          <ComponentRow
            key={slot.type}
            type={slot.type}
            label={slot.label}
            category={slot.category || slot.label}
            icon={slot.icon}
          />
        ))}
      </div>

      {/* Summary Sidebar */}
      <div className="lg:col-span-1">
        <div className="sticky top-24 space-y-6">
          <div className="rounded-2xl border border-white/10 bg-white/5 backdrop-blur-xl p-6 shadow-2xl">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-bold text-xl flex items-center gap-2">
                <span className="h-8 w-1 bg-primary rounded-full" />
                Build Summary
              </h3>
              
              {Object.keys(components).length > 0 && (
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button variant="ghost" size="sm" className="text-destructive hover:text-destructive hover:bg-destructive/10 h-8 px-2">
                      <Trash2 className="h-4 w-4 mr-1" /> Clear
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>Are you sure?</AlertDialogTitle>
                      <AlertDialogDescription>
                        This will remove all components from your current build. This action cannot be undone.
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>Cancel</AlertDialogCancel>
                      <AlertDialogAction onClick={clearBuild} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
                        Clear Build
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              )}
            </div>
            
            <div className="space-y-4 mb-8">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Components Selected</span>
                <span className="font-mono font-medium bg-secondary px-2 py-0.5 rounded text-xs">
                  {Object.keys(components).length} / {COMPONENT_SLOTS.length}
                </span>
              </div>
              <div className="h-px bg-border/50" />
              <div className="flex justify-between items-end">
                <span className="font-medium text-lg">Total</span>
                <span className="text-3xl font-bold text-primary tracking-tight">৳{totalPrice.toLocaleString()}</span>
              </div>
            </div>

            <Button 
              className="w-full font-bold shadow-lg shadow-primary/25 h-12 text-base bg-gradient-to-r from-primary to-purple-600 hover:from-primary/90 hover:to-purple-600/90 transition-all duration-300" 
              size="lg"
              onClick={handleDownloadPDF}
              disabled={Object.keys(components).length === 0}
            >
              Download Quotation
            </Button>
            
            <p className="text-[10px] text-muted-foreground text-center mt-4 leading-relaxed opacity-70">
              * Prices are subject to change. This is an estimated quotation generated by TechNexus.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
