import { getSlotDefinition } from "@/lib/pc-builder/slots";

const CURRENCY = "BDT";

function formatAmount(value) {
  return `${CURRENCY} ${Number(value || 0).toLocaleString("en-US")}`;
}

export async function downloadBuildQuotation({
  items = [],
  subtotal = 0,
  wattage = 0,
  psuWattage = null,
  issues = [],
}) {
  const [jspdfModule, autoTableModule] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);

  const JsPDF = jspdfModule.jsPDF ?? jspdfModule.default;
  const autoTable = autoTableModule.default ?? autoTableModule.autoTable;

  const doc = new JsPDF();
  const quoteNumber = `RNX-${Date.now().toString(36).toUpperCase()}`;
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);
  doc.text("PC Build Quotation", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Quotation: ${quoteNumber}`, 14, 28);
  doc.text(`Date: ${today}`, 14, 33);
  doc.text("Generated by RigNexus PC Builder", 14, 38);

  const visibleItems = items.filter((item) => item.product);

  const tableBody = visibleItems.map((item) => {
    const slot = getSlotDefinition(item.slotKey);
    const unitPrice =
      item.product.discountedPrice ?? item.product.price ?? 0;

    return [
      slot?.label ?? item.slotKey,
      item.product.name,
      formatAmount(unitPrice),
    ];
  });

  autoTable(doc, {
    startY: 46,
    head: [["Component", "Product", "Price"]],
    body: tableBody,
    theme: "grid",
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [29, 78, 216], textColor: 255 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 45 },
      2: { halign: "right", cellWidth: 40 },
    },
  });

  const tableEndY = doc.lastAutoTable?.finalY ?? 46;
  let cursorY = tableEndY + 10;

  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text(`Subtotal: ${formatAmount(subtotal)}`, 14, cursorY);

  cursorY += 7;
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Estimated system load: ~${wattage}W`, 14, cursorY);

  if (psuWattage) {
    cursorY += 5;
    doc.text(`Selected power supply: ${psuWattage}W`, 14, cursorY);
  }

  if (issues.length > 0) {
    cursorY += 9;
    doc.setFontSize(10);
    doc.setTextColor(180, 83, 9);
    doc.text("Notes:", 14, cursorY);

    for (const issue of issues) {
      cursorY += 5;
      doc.text(`- ${issue.message}`, 16, cursorY);
    }
  }

  cursorY += 10;
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(
    "Prices are subject to change and stock is not guaranteed. This quotation is valid for 7 days.",
    14,
    cursorY
  );

  doc.save("rignexus-pc-build.pdf");
}
