export const siteConfig = {
  name: "RigNexus",
  tagline: "Build. Upgrade. Play.",
  description:
    "Computer parts, laptops, PC Builder and tech essentials in Bangladesh. Genuine products, competitive prices and nationwide delivery.",
  supportPhone: "+880 1XXX-XXXXXX",
  supportEmail: "support@rignexus.com",
  address: "Dhaka, Bangladesh",
  hours: "Sat - Thu: 10:00 AM - 8:00 PM",
  freeDeliveryNote: "Free delivery inside Dhaka",
  emiNote: "EMI available on selected products",

  primaryNavCategories: [
    "Component",
    "Laptop",
    "Desktop",
    "Gaming",
    "Accessories",
    "Networking",
    "Office Equipment",
    "Server & Storage",
    "Camera",
    "Security",
    "Gadget",
    "TV",
    "UPS",
    "Tablet",
    "Phone",
    "Software",
    "Appliance",
  ],
};
